ALTER TABLE UM_BIZ_AUDIT
 DROP PRIMARY KEY CASCADE;

DROP TABLE UM_BIZ_AUDIT CASCADE CONSTRAINTS;

CREATE TABLE UM_BIZ_AUDIT
(
  ID                 NUMBER(10)                 NOT NULL,
  LOGIN_ID           VARCHAR2(100 CHAR)         NOT NULL,
  AUDIT_OPERATION    VARCHAR2(50 CHAR)          NOT NULL,
  AUDIT_PERMISSION   VARCHAR2(50 CHAR)          NOT NULL,
  OPER_ID            NUMBER(18)                 NOT NULL,
  OPER_TYPE          VARCHAR2(50 CHAR)          NOT NULL,
  FLAG               VARCHAR2(10 CHAR)          NOT NULL,
  DESCRIPTION        VARCHAR2(2000 CHAR)        NOT NULL,
  DATA_DESCRIPTION1  VARCHAR2(2000 CHAR),
  DATA_DESCRIPTION2  VARCHAR2(2000 CHAR),
  RECORD_TIME        DATE                       NOT NULL
)
TABLESPACE SHDIPP_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE UM_BIZ_AUDIT IS '审计信息表';

COMMENT ON COLUMN UM_BIZ_AUDIT.ID IS 'ID';

COMMENT ON COLUMN UM_BIZ_AUDIT.LOGIN_ID IS '操作人登录名';

COMMENT ON COLUMN UM_BIZ_AUDIT.AUDIT_OPERATION IS '操作类型';

COMMENT ON COLUMN UM_BIZ_AUDIT.AUDIT_PERMISSION IS '操作权限';

COMMENT ON COLUMN UM_BIZ_AUDIT.OPER_ID IS '操作对象ID';

COMMENT ON COLUMN UM_BIZ_AUDIT.OPER_TYPE IS '操作对象类型';

COMMENT ON COLUMN UM_BIZ_AUDIT.FLAG IS '成功标志位';

COMMENT ON COLUMN UM_BIZ_AUDIT.DESCRIPTION IS '描述';

COMMENT ON COLUMN UM_BIZ_AUDIT.DATA_DESCRIPTION1 IS '操作前数据描述';

COMMENT ON COLUMN UM_BIZ_AUDIT.DATA_DESCRIPTION2 IS '操作后数据描述';

COMMENT ON COLUMN UM_BIZ_AUDIT.RECORD_TIME IS '记录时间';



ALTER TABLE UM_EXCOL
 DROP PRIMARY KEY CASCADE;

DROP TABLE UM_EXCOL CASCADE CONSTRAINTS;

CREATE TABLE UM_EXCOL
(
  ID            NUMBER(10)                      NOT NULL,
  COLUMN_ID     NUMBER(10)                      NOT NULL,
  ITEM_ID       NUMBER(18)                      NOT NULL,
  COLUMN_VALUE  VARCHAR2(1000 BYTE),
  EXT_TABLE_ID  VARCHAR2(20 BYTE)               NOT NULL
)
TABLESPACE SHDIPP_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE UM_EXCOL IS 'UUMM表扩展属性表';

COMMENT ON COLUMN UM_EXCOL.ID IS '主键';

COMMENT ON COLUMN UM_EXCOL.COLUMN_ID IS '扩展属性ID';

COMMENT ON COLUMN UM_EXCOL.ITEM_ID IS '单个扩展item 的id,如果是User 表的扩展那就是userid， 如果是org 表的扩展那么就是orgid';

COMMENT ON COLUMN UM_EXCOL.COLUMN_VALUE IS '扩展属性值';

COMMENT ON COLUMN UM_EXCOL.EXT_TABLE_ID IS '用来标志是对那个表扩展，如果存放 UM_ORG表示对org表的扩展';



ALTER TABLE UM_EXT_DEFINE
 DROP PRIMARY KEY CASCADE;

DROP TABLE UM_EXT_DEFINE CASCADE CONSTRAINTS;

CREATE TABLE UM_EXT_DEFINE
(
  ID            NUMBER(10)                      NOT NULL,
  COLUMN_NAME   VARCHAR2(50 BYTE)               NOT NULL,
  COLUMN_DESC   VARCHAR2(150 BYTE),
  COLUMN_TYPE   VARCHAR2(20 BYTE)               NOT NULL,
  EXT_TABLE_ID  VARCHAR2(20 BYTE)               NOT NULL,
  IS_REQUIRED   VARCHAR2(1 CHAR)                DEFAULT 'N'                   NOT NULL,
  IS_UNQUIRE    VARCHAR2(10 CHAR)               DEFAULT 'N'                   NOT NULL,
  HTML_WIDGET   VARCHAR2(4000 CHAR)
)
TABLESPACE SHDIPP_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE UM_EXT_DEFINE IS 'UUMM表扩展属性字段定义表';

COMMENT ON COLUMN UM_EXT_DEFINE.ID IS '主键';

COMMENT ON COLUMN UM_EXT_DEFINE.COLUMN_NAME IS '名称';

COMMENT ON COLUMN UM_EXT_DEFINE.COLUMN_DESC IS '描述';

COMMENT ON COLUMN UM_EXT_DEFINE.COLUMN_TYPE IS '类型STRING,NUMBER';

COMMENT ON COLUMN UM_EXT_DEFINE.EXT_TABLE_ID IS '用户 组织 或者子系统';

COMMENT ON COLUMN UM_EXT_DEFINE.IS_REQUIRED IS '是否必填';

COMMENT ON COLUMN UM_EXT_DEFINE.IS_UNQUIRE IS '是否唯一';

COMMENT ON COLUMN UM_EXT_DEFINE.HTML_WIDGET IS 'Html控件片段';



ALTER TABLE UM_ORG
 DROP PRIMARY KEY CASCADE;

DROP TABLE UM_ORG CASCADE CONSTRAINTS;

CREATE TABLE UM_ORG
(
  ID           NUMBER(10)                       NOT NULL,
  ORG_PID      NUMBER(10)                       NOT NULL,
  ORG_CODE     VARCHAR2(30 CHAR)                NOT NULL,
  NAME         VARCHAR2(100 CHAR)               NOT NULL,
  FLAG         VARCHAR2(10 CHAR)                NOT NULL,
  MENO         VARCHAR2(200 BYTE),
  CREATE_DATE  DATE,
  MODIFY_DATE  DATE,
  RESVER1      VARCHAR2(20 BYTE),
  RESVER2      VARCHAR2(20 BYTE),
  RESVER3      VARCHAR2(20 BYTE),
  BODY_TYPE    VARCHAR2(6 CHAR),
  ISP_ORG      VARCHAR2(50 CHAR)
)
TABLESPACE SHDIPP_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE UM_ORG IS 'UUMM表组织表';

COMMENT ON COLUMN UM_ORG.ID IS '组织id';

COMMENT ON COLUMN UM_ORG.ORG_PID IS '父组织id';

COMMENT ON COLUMN UM_ORG.ORG_CODE IS '组织代码';

COMMENT ON COLUMN UM_ORG.NAME IS '组织名称';

COMMENT ON COLUMN UM_ORG.FLAG IS '0:正常 1:删除';

COMMENT ON COLUMN UM_ORG.MENO IS '备注';

COMMENT ON COLUMN UM_ORG.CREATE_DATE IS '创建时间';

COMMENT ON COLUMN UM_ORG.MODIFY_DATE IS '修改时间';

COMMENT ON COLUMN UM_ORG.RESVER1 IS '保留字段1';

COMMENT ON COLUMN UM_ORG.RESVER2 IS '保留字段2';

COMMENT ON COLUMN UM_ORG.RESVER3 IS '保留字段3';

COMMENT ON COLUMN UM_ORG.BODY_TYPE IS '集团类型';

COMMENT ON COLUMN UM_ORG.ISP_ORG IS '服务商来源';



ALTER TABLE UM_PERMISSION
 DROP PRIMARY KEY CASCADE;

DROP TABLE UM_PERMISSION CASCADE CONSTRAINTS;

CREATE TABLE UM_PERMISSION
(
  ID           NUMBER(10)                       NOT NULL,
  CODE         VARCHAR2(50 BYTE)                NOT NULL,
  NAME         VARCHAR2(100 BYTE)               NOT NULL,
  URL          VARCHAR2(200 BYTE),
  FLAG         VARCHAR2(10 CHAR)                NOT NULL,
  MENO         VARCHAR2(200 BYTE),
  CREATE_DATE  DATE,
  MODIFY_DATE  DATE,
  SUBSYS_ID    NUMBER(10)                       NOT NULL,
  PERTYPE      VARCHAR2(20 BYTE)
)
TABLESPACE SHDIPP_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE UM_PERMISSION IS 'UUMM权限表';

COMMENT ON COLUMN UM_PERMISSION.ID IS 'ID';

COMMENT ON COLUMN UM_PERMISSION.CODE IS '权限code';

COMMENT ON COLUMN UM_PERMISSION.NAME IS '权限名称';

COMMENT ON COLUMN UM_PERMISSION.URL IS '权限URL，用于ACL控制';

COMMENT ON COLUMN UM_PERMISSION.FLAG IS '0:正常 9:删除';

COMMENT ON COLUMN UM_PERMISSION.MENO IS '备注';

COMMENT ON COLUMN UM_PERMISSION.CREATE_DATE IS '创建时间';

COMMENT ON COLUMN UM_PERMISSION.MODIFY_DATE IS '修改时间';

COMMENT ON COLUMN UM_PERMISSION.SUBSYS_ID IS '子系统Id';

COMMENT ON COLUMN UM_PERMISSION.PERTYPE IS '权限类型';



ALTER TABLE UM_ROLE
 DROP PRIMARY KEY CASCADE;

DROP TABLE UM_ROLE CASCADE CONSTRAINTS;

CREATE TABLE UM_ROLE
(
  NAME          VARCHAR2(200 BYTE)              NOT NULL,
  FLAG          VARCHAR2(10 CHAR)               NOT NULL,
  MENO          VARCHAR2(1000 BYTE),
  SUBSYSTEM_ID  NUMBER(10)                      NOT NULL,
  CREATE_DATE   DATE,
  MODIFY_DATE   DATE,
  ROLE_CODE     VARCHAR2(100 BYTE)              NOT NULL,
  ID            NUMBER(10)                      NOT NULL,
  TOWINXPORTAL  VARCHAR2(2 BYTE)
)
TABLESPACE SHDIPP_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE UM_ROLE IS 'UUMM角色表';

COMMENT ON COLUMN UM_ROLE.NAME IS '角色名称';

COMMENT ON COLUMN UM_ROLE.FLAG IS '0:正常 9:删除';

COMMENT ON COLUMN UM_ROLE.MENO IS '备注';

COMMENT ON COLUMN UM_ROLE.SUBSYSTEM_ID IS '子系统Id';

COMMENT ON COLUMN UM_ROLE.CREATE_DATE IS '创建日期';

COMMENT ON COLUMN UM_ROLE.MODIFY_DATE IS '修改日期';

COMMENT ON COLUMN UM_ROLE.ROLE_CODE IS '角色code';

COMMENT ON COLUMN UM_ROLE.ID IS 'ID';



ALTER TABLE UM_ROLE_PERM
 DROP PRIMARY KEY CASCADE;

DROP TABLE UM_ROLE_PERM CASCADE CONSTRAINTS;

CREATE TABLE UM_ROLE_PERM
(
  ROLE_ID  NUMBER(10)                           NOT NULL,
  URL_ID   NUMBER(10)                           NOT NULL,
  ID       NUMBER(10)                           NOT NULL
)
TABLESPACE SHDIPP_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE UM_ROLE_PERM IS 'UUMM角色权限关系表';

COMMENT ON COLUMN UM_ROLE_PERM.ROLE_ID IS '角色Id';

COMMENT ON COLUMN UM_ROLE_PERM.URL_ID IS '权限Id';

COMMENT ON COLUMN UM_ROLE_PERM.ID IS 'ID';



ALTER TABLE UM_SUBSYSTEM
 DROP PRIMARY KEY CASCADE;

DROP TABLE UM_SUBSYSTEM CASCADE CONSTRAINTS;

CREATE TABLE UM_SUBSYSTEM
(
  SUBSYSTEM_ID     NUMBER(10)                   NOT NULL,
  NAME             VARCHAR2(100 CHAR)           NOT NULL,
  URL              VARCHAR2(200 BYTE)           NOT NULL,
  FLAG             VARCHAR2(10 CHAR)            NOT NULL,
  MENO             VARCHAR2(200 BYTE),
  CREATE_DATE      DATE,
  MODIFY_DATE      DATE,
  LOGIN_URL        VARCHAR2(500 CHAR),
  BROKER_URL       VARCHAR2(500 CHAR),
  SUB_SYSTEM_CODE  VARCHAR2(100 CHAR)           NOT NULL,
  MODIFY_PASS_URL  VARCHAR2(500 CHAR)
)
TABLESPACE SHDIPP_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE UM_SUBSYSTEM IS 'UUMM子系统表';

COMMENT ON COLUMN UM_SUBSYSTEM.SUBSYSTEM_ID IS '子系统Id';

COMMENT ON COLUMN UM_SUBSYSTEM.NAME IS '子系统名称';

COMMENT ON COLUMN UM_SUBSYSTEM.URL IS '子系统URL标识';

COMMENT ON COLUMN UM_SUBSYSTEM.FLAG IS '0:正常　9:删除';

COMMENT ON COLUMN UM_SUBSYSTEM.MENO IS '子系统备注';

COMMENT ON COLUMN UM_SUBSYSTEM.CREATE_DATE IS '子系统创建时间';

COMMENT ON COLUMN UM_SUBSYSTEM.MODIFY_DATE IS '子系统修改时间';

COMMENT ON COLUMN UM_SUBSYSTEM.LOGIN_URL IS '子系统登录页面';

COMMENT ON COLUMN UM_SUBSYSTEM.BROKER_URL IS '子系统无权限页面';

COMMENT ON COLUMN UM_SUBSYSTEM.SUB_SYSTEM_CODE IS '子系统code';

COMMENT ON COLUMN UM_SUBSYSTEM.MODIFY_PASS_URL IS '子系统修改密码页面';



ALTER TABLE UM_USER
 DROP PRIMARY KEY CASCADE;

DROP TABLE UM_USER CASCADE CONSTRAINTS;

CREATE TABLE UM_USER
(
  ID                NUMBER(18)                  NOT NULL,
  ORG_ID            NUMBER(10)                  NOT NULL,
  LOGIN_ID          VARCHAR2(100 CHAR)          NOT NULL,
  NAME              VARCHAR2(30 CHAR)           NOT NULL,
  LOGIN_PASS        VARCHAR2(50 BYTE)           NOT NULL,
  MAIL              VARCHAR2(75 BYTE),
  ADDRESS           VARCHAR2(100 CHAR),
  USER_LEVEL        VARCHAR2(1 BYTE),
  ZIP               VARCHAR2(10 BYTE),
  TELE              VARCHAR2(30 CHAR),
  MOBILE            VARCHAR2(15 BYTE),
  FLAG              VARCHAR2(10 CHAR)           NOT NULL,
  MENO              VARCHAR2(200 BYTE),
  CREATE_DATE       DATE,
  MODIFY_DATE       DATE,
  LOGIN_DATE        DATE                        DEFAULT sysdate,
  SEX               VARCHAR2(10 BYTE),
  LOGOUT_DATE       DATE,
  HANGUP_DATE       DATE,
  ERROR_TIMES       NUMBER(10)                  DEFAULT 0,
  LOGIN_TIMES       NUMBER(10)                  DEFAULT 0,
  LAST_IP           VARCHAR2(20 BYTE),
  PWD_TYPE          VARCHAR2(20 BYTE),
  USER_TYPE         VARCHAR2(1 CHAR)            NOT NULL,
  ISP_ORG           VARCHAR2(50 CHAR),
  BODY_TYPE         VARCHAR2(6 CHAR),
  CONFIRM_MOBILE    INTEGER,
  CONFIRM_EMAIL     INTEGER,
  LAST_LOGIN_TIMES  NUMBER(10)
)
TABLESPACE SHDIPP_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN UM_USER.ID IS '主键id';

COMMENT ON COLUMN UM_USER.ORG_ID IS '组织id';

COMMENT ON COLUMN UM_USER.LOGIN_ID IS '登录名';

COMMENT ON COLUMN UM_USER.NAME IS '用户名';

COMMENT ON COLUMN UM_USER.LOGIN_PASS IS '用户密码';

COMMENT ON COLUMN UM_USER.MAIL IS '邮箱';

COMMENT ON COLUMN UM_USER.ADDRESS IS '地址';

COMMENT ON COLUMN UM_USER.USER_LEVEL IS '9:超级管理员，1:子系统管理员，2:普通用户';

COMMENT ON COLUMN UM_USER.ZIP IS '邮编';

COMMENT ON COLUMN UM_USER.TELE IS '电话';

COMMENT ON COLUMN UM_USER.MOBILE IS '手机';

COMMENT ON COLUMN UM_USER.FLAG IS '状态';

COMMENT ON COLUMN UM_USER.MENO IS '备注';

COMMENT ON COLUMN UM_USER.CREATE_DATE IS '创建日期';

COMMENT ON COLUMN UM_USER.MODIFY_DATE IS '修改日期';

COMMENT ON COLUMN UM_USER.LOGIN_DATE IS '登录日期';

COMMENT ON COLUMN UM_USER.SEX IS '性别';

COMMENT ON COLUMN UM_USER.LOGOUT_DATE IS '退出时间';

COMMENT ON COLUMN UM_USER.HANGUP_DATE IS '上次登录错误时间';

COMMENT ON COLUMN UM_USER.ERROR_TIMES IS '连续登录出错累计次数';

COMMENT ON COLUMN UM_USER.LOGIN_TIMES IS '累计登录成功次数';

COMMENT ON COLUMN UM_USER.LAST_IP IS '最后登录IP地址';

COMMENT ON COLUMN UM_USER.PWD_TYPE IS '密码算法';

COMMENT ON COLUMN UM_USER.USER_TYPE IS '用户类型';

COMMENT ON COLUMN UM_USER.ISP_ORG IS '服务商来源';

COMMENT ON COLUMN UM_USER.BODY_TYPE IS '集团类型';



ALTER TABLE UM_USER_ROLE
 DROP PRIMARY KEY CASCADE;

DROP TABLE UM_USER_ROLE CASCADE CONSTRAINTS;

CREATE TABLE UM_USER_ROLE
(
  ID       NUMBER(10)                           NOT NULL,
  USER_ID  NUMBER(18)                           NOT NULL,
  ROLE_ID  NUMBER(10)                           NOT NULL
)
TABLESPACE SHDIPP_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE UM_USER_ROLE IS '用户-角色关联表';

COMMENT ON COLUMN UM_USER_ROLE.ID IS '主键';

COMMENT ON COLUMN UM_USER_ROLE.USER_ID IS '用户ID';

COMMENT ON COLUMN UM_USER_ROLE.ROLE_ID IS '角色ID';



CREATE UNIQUE INDEX PK_UMORG_CODE ON UM_ORG
(ORG_CODE)
LOGGING
TABLESPACE SHDIPP_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX PK_UM_PERMISSION ON UM_PERMISSION
(ID)
LOGGING
TABLESPACE SHDIPP_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX INDEX_UM_BIZ_AUDIT ON UM_BIZ_AUDIT
(RECORD_TIME)
LOGGING
TABLESPACE SHDIPP_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX PK_UMUSER_LOGINID ON UM_USER
(LOGIN_ID)
LOGGING
TABLESPACE SHDIPP_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX INDEX_SYSTEM_ID ON UM_ROLE
(SUBSYSTEM_ID)
LOGGING
TABLESPACE SHDIPP_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX INDEX_BIZ_AUDIT_LOGINID ON UM_BIZ_AUDIT
(LOGIN_ID)
LOGGING
TABLESPACE SHDIPP_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX PK_UM_USER ON UM_USER
(ID)
LOGGING
TABLESPACE SHDIPP_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX INDEX_UMUSERROLE_ID ON UM_USER_ROLE
(USER_ID, ROLE_ID)
LOGGING
TABLESPACE SHDIPP_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX INDEX_UMUSER_CREATETIME ON UM_USER
(CREATE_DATE)
LOGGING
TABLESPACE SHDIPP_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX PK_UM_EXCOL ON UM_EXCOL
(ID)
LOGGING
TABLESPACE SHDIPP_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX INDEX_BIZ_AUDIT_OPERTYPE ON UM_BIZ_AUDIT
(OPER_TYPE)
LOGGING
TABLESPACE SHDIPP_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX INDEX_UMUSER_FLAG ON UM_USER
(FLAG)
LOGGING
TABLESPACE SHDIPP_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX INDEX_UMORG_ORG_PID ON UM_ORG
(ORG_PID)
LOGGING
TABLESPACE SHDIPP_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX PK_UM_ROLE_PERM ON UM_ROLE_PERM
(ID)
LOGGING
TABLESPACE SHDIPP_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX INDEX_UMUSER_ORGID ON UM_USER
(ORG_ID)
LOGGING
TABLESPACE SHDIPP_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX PK_UM_USER_ROLE ON UM_USER_ROLE
(ID)
LOGGING
TABLESPACE SHDIPP_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX PK_UM_ROLE ON UM_ROLE
(ID)
LOGGING
TABLESPACE SHDIPP_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX INDEX_UM_SYS_FLAG ON UM_SUBSYSTEM
(NAME, FLAG)
LOGGING
TABLESPACE SHDIPP_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX INDEX_UMORG_FLAG ON UM_ORG
(FLAG)
LOGGING
TABLESPACE SHDIPP_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX PK_UM_ORG ON UM_ORG
(ID)
LOGGING
TABLESPACE SHDIPP_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX PK_UM_EXT_DEFINE ON UM_EXT_DEFINE
(ID)
LOGGING
TABLESPACE SHDIPP_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX PK_UM_SUBSYSTEM ON UM_SUBSYSTEM
(SUBSYSTEM_ID)
LOGGING
TABLESPACE SHDIPP_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX INDEX_BIZ_AUDIT_OPERID ON UM_BIZ_AUDIT
(OPER_ID)
LOGGING
TABLESPACE SHDIPP_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX UM_BIZ_AUDIT_PK ON UM_BIZ_AUDIT
(ID)
LOGGING
TABLESPACE SHDIPP_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX INDEX_UMORG_NAME ON UM_ORG
(NAME)
LOGGING
TABLESPACE SHDIPP_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE UM_BIZ_AUDIT ADD (
  CONSTRAINT UM_BIZ_AUDIT_PK
  PRIMARY KEY
  (ID)
  USING INDEX UM_BIZ_AUDIT_PK
  ENABLE VALIDATE);

ALTER TABLE UM_EXCOL ADD (
  CONSTRAINT PK_EXCOL_ID
  PRIMARY KEY
  (ID)
  USING INDEX PK_UM_EXCOL
  ENABLE VALIDATE);

ALTER TABLE UM_EXT_DEFINE ADD (
  CONSTRAINT PK6
  PRIMARY KEY
  (ID)
  USING INDEX PK_UM_EXT_DEFINE
  ENABLE VALIDATE);

ALTER TABLE UM_ORG ADD (
  CONSTRAINT PK_UM_ORG
  PRIMARY KEY
  (ID)
  USING INDEX PK_UM_ORG
  ENABLE VALIDATE);

ALTER TABLE UM_PERMISSION ADD (
  CONSTRAINT PK_UM_PERMISSION
  PRIMARY KEY
  (ID)
  USING INDEX PK_UM_PERMISSION
  ENABLE VALIDATE);

ALTER TABLE UM_ROLE ADD (
  CONSTRAINT PK_UM_ROLE
  PRIMARY KEY
  (ID)
  USING INDEX PK_UM_ROLE
  ENABLE VALIDATE);

ALTER TABLE UM_ROLE_PERM ADD (
  CONSTRAINT PK_UM_ROLE_PERM
  PRIMARY KEY
  (ID)
  USING INDEX PK_UM_ROLE_PERM
  ENABLE VALIDATE);

ALTER TABLE UM_SUBSYSTEM ADD (
  CONSTRAINT PK_UM_SUBSYSTEM
  PRIMARY KEY
  (SUBSYSTEM_ID)
  USING INDEX PK_UM_SUBSYSTEM
  ENABLE VALIDATE);

ALTER TABLE UM_USER ADD (
  CONSTRAINT PK_UM_USER
  PRIMARY KEY
  (ID)
  USING INDEX PK_UM_USER
  ENABLE VALIDATE);

ALTER TABLE UM_USER_ROLE ADD (
  CONSTRAINT PK_UM_USER_ROLE
  PRIMARY KEY
  (ID)
  USING INDEX PK_UM_USER_ROLE
  ENABLE VALIDATE);

